apiVersion: v2
name: k8s-infra
description: Helm chart for collecting metrics and logs in K8s
type: application
version: 0.7.0
appVersion: "0.70.0"
home: https://signoz.io
icon: https://signoz.io/img/SigNozLogo-orange.svg
keywords:
  - SigNoz
  - OpenTelemetry
  - apm
  - monitoring
  - logs
sources:
  - https://github.com/signoz/charts
  - https://github.com/open-telemetry/opentelemetry-collector-contrib
maintainers:
  - name: SigNoz
    email: hello@signoz.io
    url: https://signoz.io
  - name: prashant-shahi
    email: prashant@signoz.io
    url: https://prashantshahi.dev
