apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "queryService.fullname" . }}
data:
  prometheus.yml: |
    # my global config
    global:
      scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
      evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
      # scrape_timeout is set to the global default (10s).

    # Alertmanager configuration
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - {{ include "alertmanager.url" . }}

    # Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
    rule_files:
      # - "first_rules.yml"
      # - "second_rules.yml"
      - 'alerts.yml'

    # A scrape configuration containing exactly one endpoint to scrape:
    # Here it's Prometheus itself.
    scrape_configs: []

    remote_read:
      - url: tcp://{{ include "clickhouse.metricsUrl" . }}

  {{ if .Values.queryService.cache.enabled }}
  cache.yaml: |
    {{- toYaml .Values.queryService.cache.config | nindent 4 }}
  {{ end }}
