apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  default.conf: |-
    server {
      listen       {{ .Values.frontend.service.port }};
      server_name  _;
    {{- with .Values.frontend.nginxExtraConfig }}
      {{ . | trim | nindent 6 }}
    {{- end }}
      gzip on;
      gzip_static on;
      gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
      gzip_proxied  any;
      gzip_vary on;
      gzip_comp_level 6;
      gzip_buffers 16 8k;
      gzip_http_version 1.1;

      location / {
          if ( $uri = '/index.html' ) {
              add_header Cache-Control no-store always;
          }
          root   /usr/share/nginx/html;
          index  index.html index.htm;
          try_files $uri $uri/ /index.html;
      }

      location  ~ ^/api/(v1|v3)/logs/(tail|livetail){
        proxy_pass http://{{ include "queryService.url" . }};
        proxy_http_version 1.1;

        # connection will be closed if no data is read for 600s between successive read operations
        proxy_read_timeout 600s;

        # dont buffer the data send it directly to client.
        proxy_buffering off;
        proxy_cache off;
      }

      location /api {
        proxy_pass http://{{ include "queryService.url" . }}/api;
        proxy_http_version 1.1;

        # connection will be closed if no data is read for 600s between successive read operations
        proxy_read_timeout 600s;
      }

      # redirect server error pages to the static page /50x.html
      #
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }
