{{- if .Values.signoz.httproute.enabled -}}
{{- $fullName := include "signoz.fullname" . -}}

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "signoz.labels" . | nindent 4 }}
  {{- with .Values.signoz.httproute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- with .Values.signoz.httproute.parentRefs }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.signoz.httproute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    backendRefs:
      - group: ''
        kind: Service
        name: {{ $fullName }}
        port: {{ .Values.signoz.service.port }}
        weight: 1
{{- end }}
