{{- if and .Values.schemaMigrator.enabled .Release.IsInstall }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "schemaMigrator.fullname" . }}-init
  labels:
    {{- include "schemaMigrator.selectorLabelsInit" . | nindent 4 }}
    app.kubernetes.io/component: init-migrations
  {{- if .Values.schemaMigrator.annotations }}
  annotations:
    {{- toYaml .Values.schemaMigrator.annotations | nindent 4 }}
  {{- end }}
spec:
  template:
    metadata:
      labels:
        {{- include "schemaMigrator.selectorLabelsInit" . | nindent 8 }}
    spec:
      initContainers:
        {{- if .Values.schemaMigrator.initContainers.init.enabled }}
        - name: {{ include "schemaMigrator.fullname" . }}-init
          # todo: use schema migrator variables here
          image: {{ include "schemaMigrator.initContainers.init.image" . }}
          imagePullPolicy: {{ .Values.schemaMigrator.initContainers.init.image.pullPolicy }}
          env:
            {{- include "snippet.clickhouse-credentials" . | nindent 12 }}
          {{- with .Values.schemaMigrator.initContainers.init.command }}
          command:
            - sh
            - -c
            - until wget --user "$(CLICKHOUSE_USER):$(CLICKHOUSE_PASSWORD)" --spider -q {{ include "clickhouse.httpUrl" $ }}{{ .endpoint }}; do echo -e "{{ .waitMessage }}"; sleep {{ .delay }}; done; echo -e "{{ .doneMessage }}";
          {{- end }}
          resources:
            {{- toYaml .Values.schemaMigrator.initContainers.init.resources | nindent 12 }}
        {{- end }}
      containers:
        - name: schema-migrator
          image: {{ include "schemaMigrator.image" . }}
          imagePullPolicy: {{ .Values.schemaMigrator.image.pullPolicy }}
          env:
            {{- include "snippet.clickhouse-credentials" . | nindent 12 }}
          args:
            - "--dsn"
            - "tcp://{{ include "schemamigrator.url" . }}?username=$(CLICKHOUSE_USER)&password=$(CLICKHOUSE_PASSWORD)"
            {{- range .Values.schemaMigrator.args }}
            - {{ . | quote }}
            {{- end }}
      restartPolicy: OnFailure
{{- end }}
