apiVersion: v1
kind: Service
metadata:
  name: {{ include "alertmanager.fullname" . }}
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
{{- if .Values.alertmanager.service.annotations }}
  annotations:
    {{- toYaml .Values.alertmanager.service.annotations | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.alertmanager.service.type }}
  ports:
    - port: {{ .Values.alertmanager.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if (and (eq .Values.alertmanager.service.type "NodePort") .Values.alertmanager.service.nodePort) }}
      nodePort: {{ .Values.alertmanager.service.nodePort }}
      {{- end }}
  selector:
    {{- include "alertmanager.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "alertmanager.fullname" . }}-headless
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.alertmanager.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if or (gt .Values.alertmanager.replicaCount 1) (.Values.alertmanager.additionalPeers) }}
    - port: 9094
      targetPort: 9094
      protocol: TCP
      name: cluster-tcp
    - port: 9094
      targetPort: 9094
      protocol: UDP
      name: cluster-udp
    {{- end }}
  selector:
    {{- include "alertmanager.selectorLabels" . | nindent 4 }}
