{{- if and .Values.alertmanager.serviceAccount.create .Values.alertmanager.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "alertmanager.serviceAccountName" . }}
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
  {{- with .Values.alertmanager.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- include "signoz.imagePullSecrets" . }}
{{- end }}
