{{- if and (not .Values.otelTlsSecrets.existingSecretName) .Values.otelTlsSecrets.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "k8s-infra.fullname" . }}-tls-secrets
  labels:
    {{- include "k8s-infra.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  {{- with .Values.otelTlsSecrets }}
  cert.pem: {{ .certificate | b64enc }}
  key.pem: {{ .key | b64enc }}
  {{- if .ca }}
  ca.pem: {{ .ca | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
